services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi_app
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      HASH_SECRET: ${HASH_SECRET}
      APP_STORE_APP_URL: ${APP_STORE_APP_URL}
      GOOGLE_PLAY_APP_URL: ${GOOGLE_PLAY_APP_URL}
      CLIENT_URL: ${CLIENT_URL}
      API_URL: ${API_URL}
    volumes:
      - ./strapi_app/config:/opt/app/config
      - ./strapi_app/src:/opt/app/src
      - ./strapi_app/types:/opt/app/types
      - ./strapi_app/package.json:/opt/package.json
      - ./strapi_app/package-lock.json:/opt/package-lock.json
      - ./strapi_app/public/uploads:/opt/app/public/uploads
    ports:
      - "${STRAPI_CONTAINER_PORT}:1337"
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "${DATABASE_CONTAINER_PORT}:3306"